In [ ]:
class pawn:
    def __init__(self,team,pos):
        self.team=team #team 1 bottom, team 2 top
        self.cod=1
        self.pos=pos
    def mover(self,chessboard,newpos):
        possibilities=chessboard
        
        return chessboard

In [1]:
import numpy as np

In [12]:
tabuleiro=np.zeros((8,8))
tabuleiro[0][0]=11

[[11.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [15]:
import pandas as pd

In [16]:
import numpy as np

In [19]:
df=pd.DataFrame(teste)

In [17]:
teste=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
df.to_csv("mycsv")